// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShorterUrl.Data;

#nullable disable

namespace ShorterUrl.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241019182204_Linktable")]
    partial class Linktable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("ShorterUrl.Models.AnalyticsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClickDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("IpAdress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<int>("LinkId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Referrer")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.HasIndex("LinkModelId");

                    b.ToTable("Click", (string)null);
                });

            modelBuilder.Entity("ShorterUrl.Models.LinkModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("DATE")
                        .HasColumnName("expires_at");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("original_url");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("short_code");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ShortCode" }, "IX_URL_TOKEN")
                        .IsUnique();

                    b.ToTable("Link", (string)null);
                });

            modelBuilder.Entity("ShorterUrl.Models.AnalyticsModel", b =>
                {
                    b.HasOne("ShorterUrl.Models.LinkModel", "LinkModel")
                        .WithMany()
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShorterUrl.Models.LinkModel", null)
                        .WithMany("Analytics")
                        .HasForeignKey("LinkModelId");

                    b.Navigation("LinkModel");
                });

            modelBuilder.Entity("ShorterUrl.Models.LinkModel", b =>
                {
                    b.Navigation("Analytics");
                });
#pragma warning restore 612, 618
        }
    }
}
